### ISSUE TITLE
图表表现在手机小程序和PC小程序不一致

### ISSUE THREAD

**Issue by hooliy** [domisolo/taro-f2-react#23]
图表表现在手机小程序（宽度溢出了）和PC小程序（正常）不一致，有没有好的解决方案？
PC上的微信小程序表现正常：<img width="413" alt="image" src="https://github.com/user-attachments/assets/7241e83e-f6aa-4115-bdeb-a3214a99de34">

手机上的微信小程序就显示不对了：
![image](https://github.com/user-attachments/assets/d89c8a44-e9a5-4d6c-b925-7f5ed6f2f79c)

**Comment by domisolo** [comment]
给父元素 View 设置 overflow:hidden 呢？

**Comment by hooliy** [comment]
> 给父元素 View 设置 overflow:hidden 呢？

<img width="566" alt="image" src="https://github.com/user-attachments/assets/2ea95730-cc9f-4de2-9494-ab9a9910993f">
也是不行，设置成scroll，手机上也不会滚动

**Comment by hooliy** [comment]
模拟器上表现不出来，在真机上width都会溢出

**Comment by domisolo** [comment]
不是图表本身的问题，是布局引起的，解决方案就是父元素 overflow: hidden，子元素设置最大宽度 100%，或者试试 flex 。

**Comment by hooliy** [comment]
好的，谢谢！我试一下

**Comment by hooliy** [comment]
<img width="368" alt="image" src="https://github.com/user-attachments/assets/3c955732-1518-4684-8d20-d502f0a5f0d4">
好像与父元素的没啥关系，模拟器上确实是图表自适应父级大小了，但是真机上图表确实不会自适应，而是被截断了

**Comment by hooliy** [comment]
![image](https://github.com/user-attachments/assets/382cddaa-a2c4-4453-acbb-05fecea1f1ba)

**Comment by domisolo** [comment]
尝试这个方法定位下原因，把 View 放置在页面的第 1 层，如
```jsx
function Page() {
  return (
    <View style={{ width: '100%', height: '260px' }}>
      <F2Canvas>
        <Chart data={data}>
          <Interval x="genre" y="sold" />
        </Chart>
      </F2Canvas>
    </View>,
  )
}
```
如果问题没有解决，整理个 Demo 发出来。

**Comment by hooliy** [comment]
https://github.com/hooliy/taro-f2-demo   @domisolo

**Comment by domisolo** [comment]
把 @antv/f2 回退到 4.x ，把 taro-f2-react 回退到 1.1.1，问题解决
是 @antv/f2 5.x 版本引起的，看来 @antv/f2 5.x 版本的适配问题比较多

后面我会把 taro-f2-react latest 版本支持 @antv/f2 4.x，目前来看 4.x 的版本更稳定一些

**Comment by hooliy** [comment]
好的，谢谢！我试一下
